name: build-and-deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Publish to S3
      uses: jakejscott/aws-s3-deploy@v1.3.3
      with:
        args: --acl public-read --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: ./bin/Release/net6.0/publish
        S3_BUCKET: lambda-code-bucket-new
    - name: Update Lambda Function
      uses: aws-actions/aws-lambda-deploy@v0.1.0
      with:
        function-name: your-lambda-function-name
        s3-bucket: lambda-code-bucket-new
        s3-object: your-lambda-code-object-key # TODO:
        publish: true
      env:
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
