name: CI/CD for .NET 6 Lambda

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  LAMBDA_NAME: LibrarySqsLambda
  S3_BUCKET: lambda-code-bucket-new
  ARTIFACT_NAME: LambdaCode/LambdaCode/LibrarySqsLambda.zip
  S3_Key: LambdaCode/LambdaCode/LibrarySqsLambda.zip

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install .NET 6 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Build .NET 6 Lambda code
        run: dotnet publish -c Release -o ./publish --runtime linux-x64 ./LibrarySqsLambda/LibrarySqsLambda/src/LibrarySqsLambda/LibrarySqsLambda.csproj
   

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload code to S3
        run: aws s3 cp ./publish/ s3://${{ env.S3_BUCKET }}/${{ env.ARTIFACT_NAME }} --recursive

      - name: Create new Lambda version
        run: aws lambda create-function --function-name ${{ env.LAMBDA_NAME }} --code S3Bucket=${{ env.S3_BUCKET }},S3Key=${{ env.ARTIFACT_NAME }} --handler LibrarySqsLambda::LibrarySqsLambda.Function::FunctionHandler --runtime dotnet6 --role arn:aws:iam::105319023386:role/lambda-function-role --description "New version created from CI/CD pipeline"
